# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"\xb3\x05\n\x07NDArray\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\x1d\n\x05\x64type\x18\x65 \x01(\x0b\x32\x0e.NDArray.DType\x12\r\n\x04\x64\x61ta\x18\xc9\x01 \x01(\x0c\x12\x10\n\x07strides\x18\xad\x02 \x03(\x03\x1a\xd8\x04\n\x05\x44Type\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.NDArray.DType.Type\x12,\n\nbyte_order\x18\x65 \x01(\x0e\x32\x18.NDArray.DType.ByteOrder\x12\x0e\n\x05names\x18\xc9\x01 \x03(\t\x12+\n\x06\x66ields\x18\xad\x02 \x03(\x0b\x32\x1a.NDArray.DType.FieldsEntry\x12*\n\x08subdtype\x18\xe9\x07 \x01(\x0b\x32\x17.NDArray.DType.SubDType\x1a=\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.NDArray.DType:\x02\x38\x01\x1a<\n\x08SubDType\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.NDArray.DType.Type\x12\r\n\x05shape\x18\x65 \x03(\x03\"B\n\tByteOrder\x12\x11\n\rLITTLE_ENDIAN\x10\x00\x12\x0e\n\nBIG_ENDIAN\x10\x01\x12\n\n\x06NATIVE\x10\x02\x12\x06\n\x02NA\x10\x03\"\xd3\x01\n\x04Type\x12\x0b\n\x07\x66loat64\x10\x00\x12\x0b\n\x07\x66loat32\x10\x01\x12\x0b\n\x07\x66loat16\x10\x02\x12\x0e\n\ncomplex128\x10\x03\x12\r\n\tcomplex64\x10\x04\x12\n\n\x06uint64\x10\x05\x12\n\n\x06uint32\x10\x06\x12\n\n\x06uint16\x10\x07\x12\t\n\x05uint8\x10\x08\x12\t\n\x05int64\x10\t\x12\t\n\x05int32\x10\n\x12\t\n\x05int16\x10\x0b\x12\x08\n\x04int8\x10\x0c\x12\x08\n\x04S128\x10\r\x12\x07\n\x03S64\x10\x0e\x12\x07\n\x03S32\x10\x0f\x12\x07\n\x03S16\x10\x10\x12\x06\n\x02S8\x10\x11\x62\x06proto3')



_NDARRAY = DESCRIPTOR.message_types_by_name['NDArray']
_NDARRAY_DTYPE = _NDARRAY.nested_types_by_name['DType']
_NDARRAY_DTYPE_FIELDSENTRY = _NDARRAY_DTYPE.nested_types_by_name['FieldsEntry']
_NDARRAY_DTYPE_SUBDTYPE = _NDARRAY_DTYPE.nested_types_by_name['SubDType']
_NDARRAY_DTYPE_BYTEORDER = _NDARRAY_DTYPE.enum_types_by_name['ByteOrder']
_NDARRAY_DTYPE_TYPE = _NDARRAY_DTYPE.enum_types_by_name['Type']
NDArray = _reflection.GeneratedProtocolMessageType('NDArray', (_message.Message,), {

  'DType' : _reflection.GeneratedProtocolMessageType('DType', (_message.Message,), {

    'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
      'DESCRIPTOR' : _NDARRAY_DTYPE_FIELDSENTRY,
      '__module__' : 'data_pb2'
      # @@protoc_insertion_point(class_scope:NDArray.DType.FieldsEntry)
      })
    ,

    'SubDType' : _reflection.GeneratedProtocolMessageType('SubDType', (_message.Message,), {
      'DESCRIPTOR' : _NDARRAY_DTYPE_SUBDTYPE,
      '__module__' : 'data_pb2'
      # @@protoc_insertion_point(class_scope:NDArray.DType.SubDType)
      })
    ,
    'DESCRIPTOR' : _NDARRAY_DTYPE,
    '__module__' : 'data_pb2'
    # @@protoc_insertion_point(class_scope:NDArray.DType)
    })
  ,
  'DESCRIPTOR' : _NDARRAY,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:NDArray)
  })
_sym_db.RegisterMessage(NDArray)
_sym_db.RegisterMessage(NDArray.DType)
_sym_db.RegisterMessage(NDArray.DType.FieldsEntry)
_sym_db.RegisterMessage(NDArray.DType.SubDType)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NDARRAY_DTYPE_FIELDSENTRY._options = None
  _NDARRAY_DTYPE_FIELDSENTRY._serialized_options = b'8\001'
  _NDARRAY._serialized_start=15
  _NDARRAY._serialized_end=706
  _NDARRAY_DTYPE._serialized_start=106
  _NDARRAY_DTYPE._serialized_end=706
  _NDARRAY_DTYPE_FIELDSENTRY._serialized_start=301
  _NDARRAY_DTYPE_FIELDSENTRY._serialized_end=362
  _NDARRAY_DTYPE_SUBDTYPE._serialized_start=364
  _NDARRAY_DTYPE_SUBDTYPE._serialized_end=424
  _NDARRAY_DTYPE_BYTEORDER._serialized_start=426
  _NDARRAY_DTYPE_BYTEORDER._serialized_end=492
  _NDARRAY_DTYPE_TYPE._serialized_start=495
  _NDARRAY_DTYPE_TYPE._serialized_end=706
# @@protoc_insertion_point(module_scope)
